// @generated by protoc-gen-connect-es v0.8.4 with parameter "target=ts"
// @generated from file depot/cloud/v2/token.proto (package depot.cloud.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {MethodKind} from '@bufbuild/protobuf'
import {GetCacheRegistryRequest, GetCacheRegistryResponse} from './token_pb.js'

/**
 * @generated from service depot.cloud.v2.TokenService
 */
export const TokenService = {
  typeName: 'depot.cloud.v2.TokenService',
  methods: {
    /**
     * @generated from rpc depot.cloud.v2.TokenService.GetCacheRegistry
     */
    getCacheRegistry: {
      name: 'GetCacheRegistry',
      I: GetCacheRegistryRequest,
      O: GetCacheRegistryResponse,
      kind: MethodKind.Unary,
    },
  },
} as const
